Fix valgrind memory issue
GENIVI/dlt-daemon pull request #250
Opened 2020-09-27 10:27 UTC by mawillers

This changeset fixes a memory access error reported by valgrind:

==21924== Conditional jump or move depends on uninitialised value(s)
==21924==    at 0x4C30F78: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21924==    by 0x4E4B5A0: dlt_print_id (dlt_common.c:303)
==21924==    by 0x4E4CF47: dlt_message_header_flags (dlt_common.c:687)
==21924==    by 0x4E51434: dlt_message_print_ascii (dlt_common.c:3169)
==21924==    by 0x4E4247A: dlt_user_print_msg (dlt_user.c:4108)
==21924==    by 0x4E46D92: dlt_user_log_send_log (dlt_user.c:3670)
==21924==    by 0x4E46F14: dlt_user_log_write_finish (dlt_user.c:1611)

2020-10-26 02:55 UTC, thanhbnq requested changes

2020-10-26 02:55 UTC, thanhbnq commented on src/shared/dlt_common.c
> +    size_t len = (int)dlt_strnlen_s(id, DLT_ID_SIZE);
Please do not type casting here!

2020-11-10 08:37 UTC, ssugiura commented
@mawillers Sorry for my late review. Can you squash all the commits? Also please add signed-off line into your commit message like you've done in https://github.com/GENIVI/dlt-daemon/pull/223. Thank you!

2020-11-11 22:50 UTC, mawillers commented
Done. Please re-check.

2020-11-17 00:27 UTC, merged