WIP: Add support for logging with VSOCK sockets
GENIVI/dlt-daemon pull request #255
Opened 2020-10-22 16:26 UTC by martin-ejdestig

For more information about VSOCK, see `man vsock` ( https://man7.org/linux/man-pages/man7/vsock.7.html ).

Makes it possible for processes in a virtual machine to log directly in DLT running on host without setting up a network connection between guest and host. It is also probably more efficient. Have not done any performance measurements (not main reason for patch), but no networking stack is involved with VSOCK and there is also no forwarding as when running DLT in a multi-node setup.

When building dlt-daemon for host, `WITH_DLT_DAEMON_VSOCK_IPC` should be enabled for daemon to listen on incoming VSOCK requests. Local communication method between applications and daemon is still determined with `DLT_IPC`. When building for guest, `WITH_DLT_LIB_VSOCK_IPC` should be enabled and `DLT_IPC` will be ignored, which will make libdlt open a VSOCK socket to the deamon for logging messages.

VSOCK can be tested without a virtual machine. Since `VMADDR_CID_HOST` is used by libdlt when connecting, see vsock man page, clients can be run on host to test VSOCK communication.

2020-10-22 16:33 UTC, martin-ejdestig commented
@ssugiura I want to test this a bit more before it is merged, so I added a "WIP:" prefix.

One thing to get feedback on early is if you want this to be merged in multiple commits or not. Here I have tried to do cleanups/prep work/bug fixes in smaller commits. But if you prefer one single commit, I can squash the history and write a (very ;) long commit message. (I will rebase this to our internal v2.18.5 branch, would be nice is history stayed somewhat the same for person upgrading our version sometime in the future. :)

2020-10-22 16:34 UTC, martin-ejdestig commented
@ssugiura And of course, any other feedback you have would be much appreciated as well. :)

2020-10-23 15:46 UTC, martin-ejdestig commented
I squashed all the history together. If you prefer to look at smaller (independant/cherry-pickable) commits, I saved to branch with multiple commits here: https://github.com/martin-ejdestig/dlt-daemon/commits/vsock-split

If it is preferable to merge multiple commits, I can push it to this pr.

2020-10-23 15:57 UTC, martin-ejdestig commented on src/daemon/dlt_daemon_common.c
> +    if (user_list != NULL) { /* TODO: NULL check not needed? If app and no user list => bigger propblems... */
Almost certain that NULL check is not needed, but should I leave it?

2020-10-23 15:59 UTC, martin-ejdestig commented on src/daemon/dlt_daemon_common.c
> +            dlt_daemon_application_reset_user_handle(daemon, app, verbose);
Perhaps add a NULL check here (even though I am not certain app can ever be NULL)?

2020-10-25 08:36 UTC, martin-ejdestig commented on src/lib/dlt_user.c
> +                 DLT_USER_IPC_PATH);
Wrong number of args for format string. Will fix.

2020-10-26 13:11 UTC, martin-ejdestig commented on src/daemon/dlt_daemon_common.c
> +    if (user_list != NULL) { /* TODO: NULL check not needed? If app and no user list => bigger propblems... */
Noticed misspelled "propblems". Decided to remove TODO.

2020-10-28 08:55 UTC, martin-ejdestig commented on src/daemon/dlt_daemon_common.c
> +            dlt_daemon_application_reset_user_handle(daemon, app, verbose);
I added a NULL check here now (since I am not sure, better to have NULL check in our branch for now).

Leaving issue open to potentially remove it.

2020-11-10 08:39 UTC, ssugiura commented
@martin-ejdestig Is this still in WIP or can I start to review?

2020-11-10 10:08 UTC, martin-ejdestig commented
I am seeing some problems on target system I am trying to run it on. E.g. messages do not show up until client exits and if client restarts there are no messages received. I am not able to reproduce this on my Linux desktop though but would still like to investigate some more... in case there are problems with the patch.

But I think it is ready for review (since it works on vanilla Linux). I will remove the WIP prefix in subject. Would appreciate feedback. :)

2020-12-08 05:01 UTC, ssugiura requested changes
I'm very sorry for my late response.
Can you explain the changes in documents too, e.g. README.md for cmake options and doc/dlt_design_specification.md for brief explanation of usage and design.

2020-12-10 14:55 UTC, martin-ejdestig commented on src/daemon/dlt-daemon.c
> +#   ifdef __QNXNTO__
Hum, I can not find any other ifdef:s for QNX. (And from looking at e.g. https://developer.blackberry.com/playbook/native/documentation/com.qnx.doc.neutrino.prog/topic/devel_neutrino_specific.html it effectively does not matter, I think. QNX 4 is ~20 years old. :) But have changed to `ifdef __QNX__` locally, and will push once I have had time to finish documentation as well.

2020-12-13 15:08 UTC, martin-ejdestig commented on src/daemon/dlt-daemon.c
> +#   ifdef __QNXNTO__
Done.

2020-12-13 15:08 UTC, martin-ejdestig commented on src/lib/dlt_user.c
> +#   ifdef __QNXNTO__
Done.

2020-12-13 15:09 UTC, martin-ejdestig commented
> Can you explain the changes in documents too, e.g. README.md for cmake options and doc/dlt_design_specification.md for brief explanation of usage and design.

Done.

2020-12-14 00:41 UTC, ssugiura commented on src/daemon/dlt-daemon.c
> +#   ifdef __QNXNTO__
Oops, I grepped in wrong branch, sorry. But thanks for taking care of it anyways.

2020-12-14 00:43 UTC, merged